version: "3.8"
services:
  frontend:
    stdin_open: true
    tty: true
    entrypoint: sh -c "./start_frontend.sh"
    env_file:
      - .env
    container_name: frontend
    build:
      context: .
      dockerfile: react.dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./src/SE104_CoffeeShop_FE:/app
      - ./.env:/app/.env
      - ./start_frontend.sh:/app/start_frontend.sh
    environment:
      - NODE_ENV=production
      - CI=true
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    container_name: backend
    stdin_open: true
    entrypoint: sh -c "./start_backend.sh"
    tty: true
    env_file:
      - .env
    build:
      context: .
      dockerfile: laravel.dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./src/SE104_CoffeeShop_BE:/app
      - ./docker/logs:/app/storage/logs
      - ./.env:/app/.env
      - ./start_backend.sh:/app/start_backend.sh
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_NAME: ${APP_NAME}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    container_name: db
    env_file:
      - .env
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    image: nginx:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
      - ./src/SE104_CoffeeShop_FE:/app
      - ./src/SE104_CoffeeShop_BE:/app
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
